In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
%cd /gdrive/

/gdrive


In [ ]:
#Time Distributed layer is used here as we have several images/frames that are chronologically ordered and we need to make a prediction of the sequence

from keras.layers import TimeDistributed, Dense, LSTM, Dropout, Input, Flatten, Reshape, GlobalAveragePooling2D
from keras.models import Model, Sequential
from keras.models import Sequential
from keras.layers import Dense
#Dense used to obtain each input from neuron in prev layer to current one
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Input
from keras.layers import Reshape
from keras.layers import GlobalAveragePooling2D

#We have both Flatten and GlobalAveragePooling 2D.Flatten transforms a tensor to 1-D keeping all values
#The other applies average pooling on the dimensions until the spatial dimension is one(can be 1D/2D/3D)

from tensorflow.keras.applications.inception_v3 import InceptionV3

In [ ]:
"""from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D , MaxPooling1D , LSTM, TimeDistributed, Flatten
from tensorflow.keras.optimizers import Adam"""

In [ ]:
import tensorflow as tf
#from keras.layers import TimeDistributed, GRU, Dense, Dropout
from tensorflow.keras.layers import Flatten, GRU, Dropout, TimeDistributed, Dense


In [ ]:
from PIL import Image

*InceptionV3 is a Keras Image classification model loaded with weights pre-trained on the ImageNet.Pooling can be avg,max(2D) or none(4D tensor o/p of last conv block)*

In [ ]:
input_shape =(250,250,3)
data_dir = '/gdrive/MyDrive/Colab Notebooks/DeepFake'

In [ ]:
from tensorflow.python.keras.preprocessing.image import img_to_array
import os
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, load_img, array_to_img
from sklearn.model_selection import train_test_split
import numpy as np
X= []
Y= []

real = ('/gdrive/MyDrive/Colab Notebooks/DeepFake/Real/RealFrames')
fake= ('/gdrive/MyDrive/Colab Notebooks/DeepFake/Fake/FakeFrames')
real_data = os.listdir(real)[0:25]

fake_data = os.listdir(fake)[0:25]

for img in real_data:
  real_join = os.path.join(real,img)
  #print(real_join)
  X.append(img_to_array(load_img(real_join)).flatten()/255.0)
  Y.append(1)
for img in fake_data: 
  fake_join = os.path.join(fake,img)
  print(fake_join)
  X.append(img_to_array(load_img(fake_join)).flatten()/255.0)
  Y.append(0)

Y_or= Y

#Performing Normalization
X= np.array(X)
Y = to_categorical(Y,2)
print(X.shape)    
print(X.size)    
print(len(X))     

X= np.reshape(1440,1440,3)
#print(X)

X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size = 0.2, random_state=5)


In [ ]:
base_model = InceptionV3(input_shape = (250,250,3),include_top=False, weights='imagenet')
#Making all the layers non-trainable so that we can increase performance
# We use ADAM Optimizer
for layer_model in base_model.layers:
  layer_model.trainable = False

In [ ]:
pip list | grep tensorflow

tensorflow                    2.5.0              
tensorflow-datasets           4.0.1              
tensorflow-estimator          2.5.0              
tensorflow-gcs-config         2.5.0              
tensorflow-hub                0.12.0             
tensorflow-metadata           1.1.0              
tensorflow-probability        0.13.0             


In [ ]:
model = Sequential()
model.add(TimeDistributed(base_model,input_shape=(None,45,250,250,3)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(2048,dropout=0.5,return_sequences=False))
model.add(Dense(512))
model.add(Dense(1,activation="sigmoid"))
#relu helps models to overcome the vanishing gradient issue allowing them to learn faster and better performance

#model.compile(optimizer = 'Adam', loss = 'categorical_crossentropy')

In [ ]:
from keras.optimizers import Adam
#binary cross entropy used because each classification can be reduced to a binary choice (here Pristine or DeepFake)
model.compile('adam',loss='categorical_crossentropy')

In [ ]:
print(base_model.summary())

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import os
from tqdm.notebook import tqdm
import cv2
from keras.preprocessing import image
import matplotlib.pyplot as plt

In [ ]:
#Paths to respective pristine and deepfake directories
train_data_dir_pristine = '/gdrive/MyDrive/Colab Notebooks/DeepFake/Real/Pristine'
train_data_dir_fake = '/gdrive/MyDrive/Colab Notebooks/DeepFake/Fake/Deepfake'

In [ ]:
 train_data_dir_pristine

'/gdrive/MyDrive/Colab Notebooks/DeepFake/Real/Pristine'

In [ ]:
pristine_data = os.listdir(train_data_dir_pristine)[0:25]
deepfake_data = os.listdir(train_data_dir_fake)[0:25]

In [ ]:
from PIL import Image

In [ ]:
"""import sys
from PIL import Image
sys.modules['Image'] = Image

from keras.preprocessing import image
for images in tqdm(os.listdir(train_data_dir_pristine)):
  #print(images)
  filename = os.path.join(train_data_dir_pristine,images)
  print('filename',filename)
  img_chk = image.load_img(filename,target_size=(250,250,3))
  img_chk = image.img_to_array(img_chk)

img_chk """

In [ ]:
from keras.preprocessing import image
training_data_X = []
for images in tqdm(pristine_data):
  filename = os.path.join(train_data_dir_pristine,images)
  """img_pris_load = image.load_img(filename, target_size=(250,250,3)) #Load image from dir
  img_to_arr_pris = image.img_to_array(img_pris_load) #Convert the image to np array.
  img_to_arr_pris = np.expand_dims(img_to_arr_pris, axis=0) 
  training_data_X = np.vstack([img_to_arr_pris])"""
  img = cv2.imread(filename)
  training_data_X.append(img)
  print(img)
  #rg = plt.imshow(image.array_to_img(training_data_X_Pristine[0]))

[[[ 25  30  39]
  [ 24  29  38]
  [ 23  28  37]
  ...
  [187 199 193]
  [187 199 193]
  [187 199 193]]

 [[ 23  28  37]
  [ 23  28  37]
  [ 23  28  37]
  ...
  [186 198 192]
  [186 198 192]
  [187 199 193]]

 [[ 22  27  36]
  [ 22  27  36]
  [ 22  27  36]
  ...
  [186 198 192]
  [186 198 192]
  [187 199 193]]

 ...

 [[102 114 142]
  [102 114 142]
  [101 113 141]
  ...
  [ 28  74  55]
  [ 27  76  54]
  [ 27  76  54]]

 [[102 114 142]
  [101 113 141]
  [102 113 141]
  ...
  [ 27  73  54]
  [ 26  75  53]
  [ 27  76  54]]

 [[101 113 141]
  [101 113 141]
  [102 113 141]
  ...
  [ 28  74  55]
  [ 27  76  54]
  [ 28  77  55]]]
[[[ 26  32  39]
  [ 26  32  39]
  [ 26  32  39]
  ...
  [182 199 195]
  [183 200 196]
  [183 200 196]]

 [[ 27  33  40]
  [ 27  33  40]
  [ 27  33  40]
  ...
  [182 199 195]
  [183 200 196]
  [183 200 196]]

 [[ 28  34  41]
  [ 28  34  41]
  [ 28  34  41]
  ...
  [182 199 195]
  [183 200 196]
  [183 200 196]]

 ...

 [[102 113 141]
  [102 113 141]
  [102 113 141]
  ..

In [ ]:
print(training_data_X)

In [ ]:
training_data_Y_Pristine = np.full((len(pristine_data),1),'Pristine')
#array with Pristine label for all images in the X[] array

In [ ]:
#For Deepfakes respectively
for images in tqdm(deepfake_data):
  image = cv2.imread(train_data_dir_fake+images)
  training_data_X.append(image)
training_data_Y_Deepfake = np.full((len(deepfake_data),1),'Deepfake')

In [ ]:
#combining both the deepfake and pristine arrays together
#since both arrays have different number of rows we cannot use np.stack, we use .vstack
training_data_Y = np.vstack([training_data_Y_Pristine,training_data_Y_Deepfake])

In [ ]:
print (training_data_Y.shape)

(50, 1)


In [ ]:
from sklearn import preprocessing
#we can use OneHotEncoder or Lbl. Lbl assigns unique values to each label in the categorical feature
lbl = preprocessing.LabelBinarizer()
training_data_Y = lbl.fit_transform(training_data_Y)

In [ ]:
training_data_X = np.asarray(training_data_X)
training_data_X = training_data_X.reshape(25,2)
training_data_X

In [ ]:
training_data_Y = np.asarray(training_data_Y)
training_data_Y = training_data_Y.reshape(25,2)

In [ ]:
training_data_X = np.asarray(training_data_X).astype('float32')
training_data_Y = np.asarray(training_data_Y).astype('float32')

In [ ]:
mfit = model.fit(
          np.array(training_data_X),
          np.array(training_data_Y),
          steps_per_epoch=10,
          epochs=100,
          verbose=1
)